name: qnn
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ffmpeg
  - pip
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - pip:
    - -r requirements.txt
    - triton