defaults:
  - hydra
  - model: efficient_ssd
  - data: xvfi
  - override hydra/job_logging: none
  - _self_

exp_name: training_run/${model.name}
num_epoch: 5
gradient_accumulation_steps: 2
git_sha: ???

loss:
  name: l1_loss

logging:
  tensorboard_dir: ${data.folder}/${model.name}/tensorboard
  scalar_interval: 5
  image_interval: 50
  num_images: 8

bocpd_gamma:
  min: 8e-5
  max: 1e-3

photon_cube:
  min_probability: 0.6
  max_probability: 1.0

optim:
  lr: 1e-4
  betas: [0.9, 0.99]
  weight_decay: 0

# lr scheduler (cosine annealing)
scheduler:
    eta_min: 1e-8

hydra:
  output_subdir: null